name: Deploy Python Web App with Dockerfile to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t my-python-web-app .

    - name: Setup Render
      run: |
        echo "Setup Render"
        echo "${{ secrets.RENDER_API_KEY }}" | render setup
        
    - name: Deploy to Render
      run: |
        echo "Deploying to Render"
        render create --docker-image=my-python-web-app --env-file=env.list --port=8000
