name: Deploy Python App to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
         dockerfile_directory: ./

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: Dockerfile

          # (Optional, default: "")
          # Additional options of docker build command.
          docker_options: "--no-cache"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build App
      run: python app.py sdist

    # - name: Build Docker image
    #   run: docker build -t my-python-app .

    - name: Setup Render
      run: |
        echo "Setup Render"
        echo "${{ secrets.RENDER_API_KEY }}" | render setup
        
    - name: Deploy to Render
      run: |
        echo "Deploying to Render"
        render deploy --service-id=${YOUR_SERVICE_ID} --no-start --docker-image=my-python-app
