name: Deploy Python Web App with Dockerfile to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t my-python-web-app .
      
    - name: Create service on Render
      run: |
        echo "Creating service on Render"
        curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" -d '{"image": "my-python-web-app","env": {"PORT": "8000"}}' https://api.render.com/v1/services?limit=20
        
    - name: Deploy to Render
      run: |
        echo "Deploying to Render"
        curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" https://api.render.com/v1/services?limit=20/${{ env.SERVICE_ID }}/deploy
