name: Deploy to Deta
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t dockerfile .
    - name: Create Micro on Deta
      run: |
        echo "Creating Micro on Deta"
        export MICRO_NAME="my-micro"
        export DETA_API_KEY=${{ secrets.RENDER_API_KEY }}
        export RUNTIME="python"
        export DET_API_URL="https://database.deta.sh/v1"
        export MICRO_ID=`curl -H "Authorization: Bearer $DETA_API_KEY" -X POST -d '{"name":"'$MICRO_NAME'","runtime":"'$RUNTIME'"}' $DET_API_URL/micros | jq -r '.micro_id'`
    - name: Deploy to Deta
      run: |
        echo "Deploying to Deta"
        export MICRO_NAME="my-micro"
        export DETA_API_KEY=${{ secrets.RENDER_API_KEY }}
        export IMAGE_NAME="my-python-web-app"
        export PORT="8000"
        export DET_API_URL="https://database.deta.sh/v1"
        export MICRO_URL="https://$MICRO_NAME.micro.deta.sh"
        curl -H "Authorization: Bearer $DETA_API_KEY" -X PUT -d '{"image":"'$IMAGE_NAME'","env":{"PORT":"'$PORT'"}}' $DET_API_URL/micros/$MICRO_ID
